#!/bin/bash
# Template Version: 6 | ContextKit: 0.2.0 | Updated: 2025-12-16

# Custom Claude Code statusline:
# Format: Chat: ████░░░░░░ 44% (87k/200k) | 5h-Usage: 61% (2.3h left)
# With colored progress bar for chat context
#
# Usage: CustomStatusline.sh --plan Pro|Max5|Max20
# Plan parameter is required for accurate cost tracking

# ⚠️ FOR DEVELOPERS: Do not edit this file - changes will be overwritten during ContextKit updates.
# Report bugs: https://github.com/FlineDev/ContextKit/issues

# Read stdin JSON from Claude Code
input=$(cat)

# Color definitions
YELLOW='\033[33m'       # Normal yellow
RED='\033[31m'          # Bright red
LIGHT_GRAY='\033[37m'   # Light gray text
RESET='\033[0m'

# Parse command line arguments
PLAN=""  # No default - must be specified

while [[ $# -gt 0 ]]; do
    case $1 in
        --plan)
            PLAN="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 --plan Pro|Max5|Max20"
            echo "Plan is required for accurate cost tracking"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 --plan Pro|Max5|Max20"
            exit 1
            ;;
    esac
done

# Validate that plan was provided
if [[ -z "$PLAN" ]]; then
    echo "Error: --plan parameter is required"
    echo "Usage: $0 --plan Pro|Max5|Max20"
    exit 1
fi

# Set block budget based on plan
case "$PLAN" in
    "Pro")
        BLOCK_BUDGET="10.00"
        ;;
    "Max20")
        BLOCK_BUDGET="200.00"
        ;;
    "Max5")
        BLOCK_BUDGET="50.00"
        ;;
    *)
        echo "Invalid plan: $PLAN. Use Pro, Max5, or Max20"
        exit 1
        ;;
esac

# Allow environment variable override
BLOCK_BUDGET=${CLAUDE_BLOCK_BUDGET:-$BLOCK_BUDGET}

# Function to create colored progress bar and return color
create_progress_bar() {
    local percent=$1
    local width=10
    local filled=$((percent * width / 100))
    local empty=$((width - filled))

    # Choose color based on percentage
    local color
    if [[ $percent -lt 50 ]]; then
        color="$LIGHT_GRAY"
    elif [[ $percent -lt 80 ]]; then
        color="$YELLOW"
    else
        color="$RED"
    fi

    local bar=""

    # Add filled and empty portions
    for ((i=0; i<filled; i++)); do
        bar+="▓"
    done
    for ((i=0; i<empty; i++)); do
        bar+="░"
    done

    # Return both bar and color (separated by |)
    echo "${color}${bar}|${color}"
}

# Extract context window data from stdin JSON
CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000')
CURRENT_USAGE=$(echo "$input" | jq '.context_window.current_usage')

# Calculate current context usage from current_usage fields
if [[ "$CURRENT_USAGE" != "null" && -n "$CURRENT_USAGE" ]]; then
    # Current tokens = input + cache_creation + cache_read
    # (output tokens are not included in context window calculation)
    CURRENT_TOKENS=$(echo "$CURRENT_USAGE" | jq '.input_tokens + .cache_creation_input_tokens + .cache_read_input_tokens')
    context_percent=$((CURRENT_TOKENS * 100 / CONTEXT_SIZE))

    # Convert to k format for display
    tokens_k=$(((CURRENT_TOKENS + 999) / 1000))
    context_size_k=$((CONTEXT_SIZE / 1000))
else
    # Fallback if current_usage not available yet
    context_percent=0
    tokens_k=0
    context_size_k=200
fi

# Check if ccusage command exists
if ! command -v ccusage &> /dev/null; then
    ccusage_installed="false"
    ccusage_available="false"
else
    ccusage_installed="true"
    # Get ccusage data for 5h-Usage calculation
    ccusage_data=$(ccusage statusline 2>/dev/null)
    ccusage_available=$([[ $? -eq 0 && -n "$ccusage_data" ]] && echo "true" || echo "false")
fi

# Calculate 5h-Usage from ccusage if available
if [[ "$ccusage_available" == "true" ]]; then
    # Extract block time remaining (format: "block (13m left)" or "block (1h 13m left)")
    block_time=$(echo "$ccusage_data" | grep -o 'block ([^)]*left)' | sed 's/block (\|)//g')

    # Parse block cost from ccusage output (e.g., "$0.45 block (2h 45m left)")
    block_cost=$(echo "$ccusage_data" | grep -o '\$[0-9.]\+ block' | grep -o '[0-9.]\+')

    # Parse time remaining for display
    if [[ "$block_time" =~ ([0-9]+)h[[:space:]]+([0-9]+)m[[:space:]]+left ]]; then
        # Format: "1h 13m left"
        hours_left=${BASH_REMATCH[1]}
        minutes_left=${BASH_REMATCH[2]}
        total_minutes_left=$((hours_left * 60 + minutes_left))
    elif [[ "$block_time" =~ ([0-9]+)m[[:space:]]+left ]]; then
        # Format: "13m left"
        hours_left=0
        minutes_left=${BASH_REMATCH[1]}
        total_minutes_left=$minutes_left
    fi

    # Calculate cost-based percentage and format display
    if [[ -n "$block_cost" && -n "$BLOCK_BUDGET" ]]; then
        # Calculate real usage percentage based on API cost
        window_percent=$(echo "scale=0; ($block_cost * 100) / $BLOCK_BUDGET" | bc)
        if [[ $window_percent -gt 100 ]]; then window_percent=100; fi

        # Format time display: minutes if < 60, decimal hours if >= 60
        if [[ -n "$total_minutes_left" ]]; then
            if [[ $total_minutes_left -lt 60 ]]; then
                time_display="${total_minutes_left}m left"
            else
                # Convert to decimal hours with 1 decimal place
                hours_decimal=$(echo "scale=1; $total_minutes_left / 60" | bc)
                time_display="${hours_decimal}h left"
            fi
            window_info="5h-Usage: ${window_percent}% (${time_display})"
        else
            window_info="5h-Usage: ${window_percent}%"
        fi
    else
        window_info="5h-Usage: parsing..."
    fi
else
    # ccusage not available - distinguish between not installed vs awaiting data
    if [[ "$ccusage_installed" == "false" ]]; then
        window_info="5h-Usage: N/A (install ccusage)"
    else
        window_info="5h-Usage: N/A (awaiting usage)"
    fi
fi

# Format chat context with progress bar using built-in current_usage data
if [[ "$CURRENT_USAGE" != "null" && -n "$CURRENT_USAGE" ]]; then
    # Create colored progress bar
    progress_result=$(create_progress_bar $context_percent)
    progress_bar=$(echo "$progress_result" | cut -d'|' -f1)
    text_color=$(echo "$progress_result" | cut -d'|' -f2)

    context_info="Chat: ${progress_bar} ${text_color}${context_percent}% (${tokens_k}k/${context_size_k}k)${LIGHT_GRAY}"
else
    context_info="Chat: N/A (awaiting usage)"
fi

# Output statusline
echo -e "${LIGHT_GRAY}$context_info | $window_info${RESET}"